services:
  - type: pserv
    name: mysql
    runtime: docker
    image:
      url: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root

  - type: web
    name: spring
    runtime: docker
    repo: .  # Assuming the Dockerfile is in the repository root
    dockerfilePath: Dockerfile

